model:
  antialias: false
  arch: 'resnet18'
resolution:
  min_res: 224
  max_res: 224
  end_ramp: 0
data:
  gpu: 0
  train_dataset: '/mnt/cfs/home/engstrom/store/ffcv/train_310.ffcv'
  # val_dataset: '/mnt/cfs/home/engstrom/store/ffcv/val_310.ffcv'
  # val_dataset: '/mnt/cfs/home/engstrom/store/ffcv/val_400_0.0_100.ffcv'
  val_dataset: '/mnt/cfs/home/engstrom/store/ffcv/val_1000_1.0_100.ffcv'
  num_workers: 10
logging:
  folder: '/tmp/'
training:
  batch_size: 1024
  optimizer: "sgd"
  lr: 0.1
  eval_only: 1
  pretrained: True
  momentum: 0.9
  weight_decay: 1e-4
  epochs: 90
  label_smoothing: 0
  lr_schedule_type: 'step'
  step_ratio: 0.1
  step_length: 30
validation:
  batch_size: 2048
  resolution: 224
  lr_tta: False
