model:
  antialias: false
  arch: 'resnet18'
resolution:
  min_res: 224
  max_res: 224
  end_ramp: 0
data:
  gpu: 0
  train_dataset: '/mnt/cfs/home/engstrom/store/ffcv/train_350_0_100.ffcv'
  val_dataset: '/mnt/cfs/home/engstrom/store/ffcv/val_350_0_100.ffcv'
  num_workers: 10
logging:
  folder: '/tmp/'
training:
  batch_size: 1024
  optimizer: "sgd"
  bn_momentum: 0
  lr: 0.1
  momentum: 0.9
  weight_decay: 1e-4
  epochs: 120
  label_smoothing: 0.1
  lr_schedule_type: 'step'
  step_ratio: 0.1
  step_length: 30
  mixup_alpha: 0.2
validation:
  batch_size: 1024
  resolution: 224
  lr_tta: True
dist:
  world_size: 1
