data:
  in_memory: 1
  num_workers: 12
dist:
  world_size: 8
logging:
  folder: /tmp/
lr:
  lr: 1.7
  lr_schedule_type: cyclic
model:
  arch: resnet50
resolution:
  end_ramp: 13
  max_res: 192
  min_res: 160
  start_ramp: 11
training:
  batch_size: 512
  bn_wd: 0
  distributed: 1
  epochs: 16
  label_smoothing: 0.1
  momentum: 0.9
  optimizer: sgd
  weight_decay: 0.0001
validation:
  lr_tta: true
  resolution: 256
