data:
  gpu: 0
  in_memory: 1
  num_workers: 12
dist:
  world_size: 1
logging:
  folder: /tmp/
  log_level: 0
lr:
  lr: 0.5
  lr_peak_epoch: 2
  lr_schedule_type: cyclic
model:
  arch: resnet18
resolution:
  end_ramp: 48
  max_res: 192
  min_res: 160
  start_ramp: 41
training:
  batch_size: 1024
  bn_wd: 0
  distributed: 0
  epochs: 56
  label_smoothing: 0.1
  momentum: 0.9
  optimizer: sgd
  weight_decay: 5e-5
validation:
  lr_tta: true
  resolution: 256
